[package]
name = "gear"
version = "0.1.0"
edition = "2024"

[dependencies]
clap =  { version = "4.5.27", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
indicatif = "0.17.9"
subprocess = "0.2.9"